services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=diabeticselfed'
      - 'MYSQL_PASSWORD=selfed@2203'
      - 'MYSQL_ROOT_PASSWORD=selfed@2203'
      - 'MYSQL_USER=selfed'
    ports:
      - '3306'
