
spring:
  datasource:
    url: jdbc:postgresql:db-postgresql-nyc3-83294-do-user-15314830-0.c.db.ondigitalocean.com:25060/diabeticselfed
    username: doadmin
    password: AVNS_wj-4V8SmQwhIGQ-KGPV
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000
